name: Docker
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 22 * * 4'

jobs:
  build_archlinux:
    name: Building Archlinux docker
    runs-on: ubuntu-latest
    container:
      image: docker://archlinux:latest
      options: --user root --privileged --dns 1.1.1.1

    steps:
      - uses: actions/checkout@main

      - name: Make docker
        id: make_docker
        run: |
          echo "root:65536:65536" >> /etc/subuid
          echo "root:65536:65536" >> /etc/subgid
          pacman -Syu --noconfirm make devtools util-linux docker curl jq
          mkdir -p build output
          mkdir -vp build/alpm-hooks/usr/share/libalpm/hooks
          mkdir -vp build/var/lib/pacman/ output
          packages=(base base-devel jq openssh git mercurial subversion ninja cmake ragel yasm nasm asciidoc enca gperf unzip p7zip gcc-multilib clang lld libc++ libc++abi python-cairo python-pip curl lib32-glib2 wget mimalloc ccache)
          find /usr/share/libalpm/hooks -exec ln -sf /dev/null build/alpm-hooks{} \;
          install -Dm644 /usr/share/devtools/pacman.conf.d/extra.conf build/etc/pacman.conf
          cat pacman-conf.d-noextract.conf >> build/etc/pacman.conf
          cp --recursive --preserve=timestamps --backup --suffix=.pacnew rootfs/* build/
          unshare --map-root-user --map-auto -- pacman -Sy -r build --noconfirm --dbpath build/var/lib/pacman --config build/etc/pacman.conf --noscriptlet --hookdir build/alpm-hooks/usr/share/libalpm/hooks/ ${packages[@]}
          unshare --map-root-user --map-auto -- chroot build update-ca-trust
          unshare --map-root-user --map-auto -- chroot build bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf && pip3 install --no-cache-dir --upgrade --break-system-packages setuptools rst2pdf mako jsonschema meson'
          unshare --map-root-user --map-auto -- chroot build bash -c 'mkdir -p etc/pacman.d/gnupg && pacman-key --init && pacman-key --populate && rm -rf etc/pacman.d/gnupg/{openpgp-revocs.d/,private-keys-v1.d/,pubring.gpg~,gnupg.S.}*'
          ln -fs /usr/lib/os-release build/etc/os-release
          # add system users
          unshare --map-root-user --map-auto -- chroot build /usr/bin/systemd-sysusers --root "/"
          # remove passwordless login for root (see CVE-2019-5021 for reference)
          sed -i -e 's/^root::/root:!:/' "build/etc/shadow"
          # fakeroot to map the gid/uid of the builder process to root
          # fixes #22
          unshare --map-root-user --map-auto -- tar --numeric-owner --xattrs --acls --exclude-from=exclude -C build -c . -f output/rootfs.tar
          cd output; zstd --long -T0 -8 rootfs.tar; cd ..

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.workflows
          push: true
          provenance: false
          tags: ghcr.io/${{ github.actor }}/archlinux:latest

      - name: Upload bootstrap artifact
        uses: actions/upload-artifact@main
        with:
          name: rootfs
          path: output/rootfs.tar.zst

      - name: Delete untagged docker
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          package_id=$(curl -su shinchiro:$GH_TOKEN -X GET -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/packages/container/archlinux/versions | jq -r 'map(select(.metadata.container.tags | length == 0)) | .[].id')
          for id in ${package_id[@]}; do
            curl -su shinchiro:$GH_TOKEN -X DELETE -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/packages/container/archlinux/versions/$id
          done
